# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  license: Apache-2.0
  images: |
    - image: docker.io/bitnami/chainloop-artifact-cas:0.95.3-debian-12-r0
      name: artifact-cas
    - image: docker.io/bitnami/chainloop-control-plane:0.95.3-debian-12-r0
      name: control-plane
    - image: docker.io/bitnami/chainloop-control-plane-migrations:0.95.3-debian-12-r0
      name: control-plane-migrations
    - image: docker.io/bitnami/dex:2.40.0-debian-12-r1
      name: dex
apiVersion: v2
appVersion: 0.95.3
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.x.x
  - condition: development
    name: vault
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 1.4.x
description: Chainloop is an open source software supply chain control plane, a single source of truth for artifacts plus a declarative attestation crafting process.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/chainloop/img/chainloop-stack-220x234.png
keywords:
  - chainloop
  - evidence-store
  - supply-chain-security
  - devops
  - devsecops
  - security
  - compliance
  - cyclonedx
  - spdx
  - sbom
  - attestation
  - oss-compliance
  - in-toto
  - slsa
  - sbom-distribution
  - open-source-licensing
  - slsa-provenance
  - metadata-platform
  - sbom-discovery
  - regulated-industry
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: chainloop
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/chainloop
  - https://github.com/bitnami/containers/tree/main/bitnami/chainloop-control-plane
  - https://github.com/bitnami/containers/tree/main/bitnami/chainloop-control-plane-migrations
  - https://github.com/bitnami/containers/tree/main/bitnami/chainloop-artifact-cas
  - https://github.com/chainloop-dev/chainloop
version: 0.1.1
